import { useEffect, useState } from 'react';
import PresignedUploadFlow from '../components/Upload/PresignedUploadFlow';
import TagManagementTabs from '../components/Tags/TagManagementTabs';
import { useAuth } from '../context/AuthContext';
import { plainUrl } from '../lib/apiClient';
import { useUserUploads } from '../hooks/useUserUploads';
import type { UploadRecord } from '../hooks/useUserUploads';

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleString();
}

const CopyIcon = () => (
  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <rect x="9" y="9" width="13" height="13" rx="2"/>
    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>
  </svg>
);
const CheckIcon = () => (
  <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
    <polyline points="20 6 9 17 4 12"/>
  </svg>
);

function CopyUrlButton({ text, label, disabled }: { text: string; label: string; disabled?: boolean }) {
  const [copied, setCopied] = useState(false);
  function copy(e: React.MouseEvent) {
    e.stopPropagation();
    if (disabled || !text) return;
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
    });
  }
  return (
    <button
      type="button"
      className={`tbl-copy-btn${disabled ? ' tbl-copy-btn--disabled' : ''}`}
      onClick={copy}
      title={disabled ? 'Not yet available — generated by ML pipeline after upload' : `Copy ${label}`}
      disabled={disabled}
    >
      {copied ? <CheckIcon /> : <CopyIcon />}
      <span>{copied ? 'Copied!' : label}</span>
    </button>
  );
}

function UploadRow({ u }: { u: UploadRecord }) {
  const isVideo = u.fileType.startsWith('video');
  return (
    <tr>
      <td className="uploads-table-filename" title={u.filename}>{u.filename}</td>
      <td>
        <span className="uploads-table-badge">{isVideo ? 'video' : 'image'}</span>
      </td>
      <td style={{ whiteSpace: 'nowrap' }}>{formatBytes(u.sizeBytes)}</td>
      <td style={{ whiteSpace: 'nowrap' }}>{formatDate(u.uploadedAt)}</td>
      <td>
        <CopyUrlButton text={plainUrl(u.url)} label="Copy URL" />
      </td>
    </tr>
  );
}

export default function DashboardPage() {
  const { userEmail } = useAuth();
  const { uploads, addUpload, refresh, clear } = useUserUploads(userEmail);

  useEffect(() => {
    function handleUploadDone(e: Event) {
      addUpload((e as CustomEvent).detail);
    }
    window.addEventListener('ecolens:upload', handleUploadDone);
    return () => window.removeEventListener('ecolens:upload', handleUploadDone);
  }, [addUpload]);

  return (
    <main className="container">
      <div className="page-title">
        <h1>Dashboard</h1>
        <p>Upload wildlife media and manage tags across your collection.</p>
      </div>

      {/* Equal-height two-column row */}
      <section className="dashboard-panels">
        <div className="card dashboard-panel">
          <PresignedUploadFlow />
        </div>
        <div className="card dashboard-panel">
          <TagManagementTabs />
        </div>
      </section>

      {/* Recently Uploaded table */}
      <section className="card" style={{ marginTop: '28px' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '20px' }}>
          <div>
            <h2 style={{ margin: 0 }}>My Recent Uploads</h2>
            <p style={{ margin: '4px 0 0', fontSize: '14px', color: 'var(--muted)' }}>
              Files uploaded in this browser session, tracked locally per account.
            </p>
          </div>
          <div style={{ display: 'flex', gap: '8px', flexShrink: 0 }}>
            <button
              className="btn btn-outline btn-icon"
              type="button"
              onClick={refresh}
              title="Refresh"
              aria-label="Refresh"
              style={{ marginTop: 0 }}
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="23 4 23 10 17 10"/>
                <path d="M20.49 15a9 9 0 1 1-2.12-9.36L23 10"/>
              </svg>
            </button>
            <button
              className="btn btn-outline btn-icon"
              type="button"
              onClick={clear}
              title="Clear history"
              aria-label="Clear history"
              style={{ marginTop: 0 }}
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="3 6 5 6 21 6"/>
                <path d="M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"/>
                <path d="M10 11v6M14 11v6"/>
                <path d="M9 6V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v2"/>
              </svg>
            </button>
          </div>
        </div>

        {uploads.length === 0 ? (
          <p style={{ color: 'var(--muted)', fontSize: '14px', textAlign: 'center', padding: '32px 0' }}>
            No uploads recorded yet. Upload a file above to see it here.
          </p>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table className="uploads-table">
              <thead>
                <tr>
                  <th>Filename</th>
                  <th style={{ width: '56px' }}>Type</th>
                  <th style={{ width: '72px' }}>Size</th>
                  <th style={{ width: '140px' }}>Uploaded At</th>
                  <th style={{ width: '120px' }}>File URL</th>
                </tr>
              </thead>
              <tbody>
                {uploads.map((u, i) => <UploadRow key={i} u={u} />)}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </main>
  );
}
